### ISSUE TITLE
Only a white page since 3 days 

### ISSUE THREAD

**Issue by phitschi** [rterp/GMapsFX#175]
Hey,
since 3 days I only get a white page.
First I thought my implementation is the problem.
But also the demo doesn't work.
I tested it with an without an API-Key.
When I started it in debug mode I got the message: ReferenceError: Can't find variable: loadMapLibrary.

Anybody else with the same problem?

Thanks

**Comment by mmihhailov** [comment]
Yes. Except on first initialization, I get white page and nothing in logs. Trying second time, it throws exception:

```
Caused by: netscape.javascript.JSException: Error: The Google Maps JavaScript API does not support this browser.
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:146)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1509)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:1005)
	at com.lynden.gmapsfx.javascript.JavaFxWebEngine.executeScript(JavaFxWebEngine.java:42)
	at com.lynden.gmapsfx.javascript.JavascriptRuntime.execute(JavascriptRuntime.java:63)
	at com.lynden.gmapsfx.javascript.JavascriptObject.<init>(JavascriptObject.java:76)
	at com.lynden.gmapsfx.javascript.object.GoogleMap.<init>(GoogleMap.java:71)
	at com.lynden.gmapsfx.GoogleMapView.internal_createMap(GoogleMapView.java:345)
	at com.lynden.gmapsfx.GoogleMapView.createMap(GoogleMapView.java:320)
	at com.lynden.gmapsfx.GoogleMapView.createMap(GoogleMapView.java:306)
```

**Comment by sergicastellsague** [comment]
I think it's related with the Mojave version. It fails for me with: macOS 10.14 (18A391)

**Comment by phitschi** [comment]
I think my problem isn't a browser problem.

**Comment by mmihhailov** [comment]
Upgrading to Java 11 and JavaFX 11 solved the problem for me. It's quite a task, but well. At least seems to do the trick.

**Comment by sergicastellsague** [comment]
I confirm @mmihhailov solution works. I had to download jdk1.8.0_181.jdk in order to have it working.

**Comment by minhdn90** [comment]
Thanks @mmihhailov. It worked for me. Upgraded to Java 11 and JavaFX 11
