### ISSUE TITLE
Exception in Application start method 

### ISSUE THREAD

**Issue by hananabilabd** [rterp/GMapsFX#176]
when i used the MainApp.java or MainApp2.java on netbeans it gives me this error , I really don't know what is the problem , I've included GMapsFX .jar version 12  and I am using JDK 8 
``
run:
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/spi/JoranException
	at org.slf4j.LoggerFactory.getSingleton(LoggerFactory.java:189)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:112)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:105)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:235)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:208)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:221)
	at com.lynden.gmapsfx.GoogleMapView.<clinit>(GoogleMapView.java:55)
	at test.GMapsFX.start(GMapsFX.java:47)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	... 1 more
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.joran.spi.JoranException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
Exception running application test.GMapsFX
``

**Comment by hananabilabd** [comment]
it's not related to slf4j as when I removed it's jar from the project it still gives me the same error

**Comment by hananabilabd** [comment]
the solution was to downgrade to to GMapsfx 10  
_____________________________________________________________________
![image](https://user-images.githubusercontent.com/26032494/49035255-f157aa00-f1bc-11e8-8d81-4a0ee7e40787.png)
I had another issue the map appear to be like that 
so how can i remove for development purpose only ?  and google message ?

**Comment by hananabilabd** [comment]
about the "for development purpose only " it turns out google maps turned not be free

**Comment by hananabilabd** [comment]
I have one final question  
How to edit this mapView in realtime ?
