### ISSUE TITLE
java.lang.IllegalArgumentException: Image dimensions must be > 0

### ISSUE THREAD

**Issue by Wackyjackie** [rterp/GMapsFX#28]
When panning and zooming a map I get this exception:

java.lang.IllegalArgumentException: Image dimensions must be > 0
	at com.sun.prism.Image.<init>(Unknown Source)
	at com.sun.prism.Image.<init>(Unknown Source)
	at com.sun.prism.Image.fromByteBgraPreData(Unknown Source)
	at com.sun.javafx.webkit.prism.RTImage.getImage(Unknown Source)
	at com.sun.javafx.webkit.prism.PrismImage.getPlatformImage(Unknown Source)
	at com.sun.javafx.webkit.UIClientImpl.startDrag(Unknown Source)
	at com.sun.webkit.WebPage.fwkStartDrag(Unknown Source)
	at com.sun.webkit.WebPage.twkProcessMouseEvent(Native Method)
	at com.sun.webkit.WebPage.dispatchMouseEvent(Unknown Source)
	at javafx.scene.web.WebView.processMouseEvent(Unknown Source)
	at javafx.scene.web.WebView.access$2500(Unknown Source)
	at javafx.scene.web.WebView$14.handle(Unknown Source)
	at javafx.scene.web.WebView$14.handle(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.event.Event.fireEvent(Unknown Source)
	at javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.scene.Scene$MouseHandler.access$1800(Unknown Source)
	at javafx.scene.Scene.impl_processMouseEvent(Unknown Source)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.access$300(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$4$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" E

**Comment by rterp** [comment]
Is this problem still occuring?

**Comment by rterp** [comment]
Not abe to replicate the issue.
