### ISSUE TITLE
Load GMapsFX library into SceneBuilder

### ISSUE THREAD

**Issue by rterp** [rterp/GMapsFX#72]
There is an exception being thrown when attempting to add the GMapsFX library to SceneBuilder which in turn is not adding the MapView component to the palette.

Exception for: com/lynden/gmapsfx/GoogleMapView.class
javafx.fxml.LoadException: 
unknown path:2

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)
	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.instantiateWithFXMLLoader(JarExplorer.java:107)
	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.exploreEntry(JarExplorer.java:154)
	at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.explore(JarExplorer.java:67)
	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.exploreAndUpdateLibrary(LibraryFolderWatcher.java:313)
	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.runDiscovery(LibraryFolderWatcher.java:142)
	at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.run(LibraryFolderWatcher.java:94)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Not on FX application thread; currentThread = LibraryFolderWatcher(/home/robt/.scenebuilder/Library)
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.web.WebEngine.checkThread(WebEngine.java:1216)
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:856)
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:845)
	at javafx.scene.web.WebView.<init>(WebView.java:271)
	at com.lynden.gmapsfx.GoogleMapView.<init>(GoogleMapView.java:193)
	at com.lynden.gmapsfx.GoogleMapView.<init>(GoogleMapView.java:157)
	at com.lynden.gmapsfx.GoogleMapView.<init>(GoogleMapView.java:135)
	at com.lynden.gmapsfx.GoogleMapView.<init>(GoogleMapView.java:75)
	at com.lynden.gmapsfx.GoogleMapView.<init>(GoogleMapView.java:71)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	... 8 more

**Comment by GeoffCapper** [comment]
Unfortunately I don't use SceneBuilder so I don't know much about it's workings, outer or inner. Is it safe to assume WebView works okay within SceneBuilder?

I thought most controls could be built on a background thread but need to be displayed on the FX one, but here the WebView is checking which thread it's on and throwing before it's even been added to a parent, much less shown.

Could we put a placeholder in the position the WebView should occupy in order to get the layout built and set up a Platform.runLater to replace it with the WebView when appropriate?

**Comment by rterp** [comment]
@GeoffCapper I should be able to take a look at this one later in the week and hopefully figure out a workable solution.

**Comment by GeoffCapper** [comment]
My humble apologies! I've just stumbled across the changes that were made to support this initially, and realised that I dumped them all not understanding what their purpose was when I was fixing the other issue... I guess restoring them will resolve this, so I'll take care of that ASAP.
https://github.com/rterp/GMapsFX/commit/022e197212dd914e3fa65e108254117b4d0fd1be

**Comment by GeoffCapper** [comment]
I've put the changes back in, hopefully that solves the problem... again ha ha!

**Comment by rterp** [comment]
Looks like that did the trick, thanks @GeoffCapper
